---
title: "Urban Fledglings"
Author: "Anja Morgenthaler"
Date: Today
toc: true
abstract-title: "Research question"
abstract: "How do environmental stressors and resource availability influence reproductive success?"
format:
  html:
    embed-resources: true
    number-sections: true
    code-fold: show
    
editor: visual
editor_options:
  chunk_output_type: console
execute:
  warning: false
  message: false
---

# Urban Fledglings - Analysis Report

## Session Preparation

```{r}
#| label: Loading libraries
#| echo: false
#load libraries
library(pastecs)
  library(ggpubr); theme_set(theme_bw())
  library(GGally)
  library(performance)
  library(MuMIn)
  library(ggeffects)
  library(knitr) 
```

```{r}
#| label: Importing data
#| echo: false

birds <- read.csv("/Users/anjam/Desktop/Fledglings07/data/processed/clean.csv")
```

## Data Exploration

### Numerically

### Graphically

## Model

### Fit Candidate Models

### Select Preffered Model

### Validate Preferred Model

## Interpretation

## Report Findings

## Store session information
